default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: eatsystreet-rails-development

test:
  <<: *default
  database: eatsystreet-rails-test

production:
  <<: *default
  database: eatsystreet-rails-production
